import Head from "next/head";
import dynamic from "next/dynamic";
import styles from "@/styles/Home.module.css";

const PlatformGame = dynamic(() => import("@/games/platform"), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.gameContainer}>
        <h1>Generate a Bitcoin unique mnemonic by catching all the coins.</h1>
        <PlatformGame />
        <p>
          Controls: Arrow keys to move left/right, Space to jump. You can
          perform a double jump in mid-air.
        </p>
        <p>
          The game stores all the keypresses and the time between each keypress,
          using this pseudo-randomic info to generate a unique 24-word Bitcoin
          private key.
        </p>
        <p>
          All of the code is generated using ChatGPT GPT-4 model. View here the
          <a
            target="_blank"
            href="https://sharechatgpt.com/share/6b92623549178bf37955c2d3d9fb8c10"
          >
            prompt history
          </a>
          .
        </p>
      </main>
    </>
  );
}
